export type BossGroup = 'surface' | 'caves' | 'lunar' | 'hamlet' | 'shipwrecked' | 'event' | 'sea' | 'seasonal' | 'miniboss';

export interface Boss {
  id: string;
  name: string;
  imageUrl: string;
  wikiUrl: string;
  description: string;
  guide: string;
  loot?: string[];
  group: BossGroup;
}

export const BOSS_GROUPS: Record<BossGroup, string> = {
  surface: 'Боссы Поверхности',
  caves: 'Боссы Пещер',
  lunar: 'Боссы Лунного Острова',
  hamlet: 'Боссы Hamlet',
  shipwrecked: 'Боссы Shipwrecked',
  event: 'Боссы Событий',
  sea: 'Морские боссы',
  seasonal: 'Сезонные боссы',
  miniboss: 'Минибоссы',
};

export const BOSS_VISIBILITY: Record<BossGroup, boolean> = {
  surface: true,
  caves: true,
  lunar: true,
  hamlet: false,
  shipwrecked: false,
  event: false,
  sea: true,
  seasonal: true,
  miniboss: true,
};

export const CROSS_OUT_ANIMATION_DURATION = 0.6;

export const BOSS_GROUP_ORDER: BossGroup[] = ['surface', 'seasonal', 'sea', 'miniboss', 'caves', 'lunar', 'hamlet', 'shipwrecked', 'event'];

export const BOSSES: Boss[] = [
  {
    id: 'ancient-fuelweaver',
    name: 'Древний Топливопряд',
    imageUrl: 'https://static.wikia.nocookie.net/dont-starve-game/images/d/df/Ancient_Fuelweaver.png',
    wikiUrl: 'https://dontstarve.fandom.com/wiki/Ancient_Fuelweaver',
    description: 'Финальный босс пещер. Призывается в Атриуме.',
    guide: 'Чтобы призвать его, нужно: 1. Собрать скелет из 8 окаменелостей в Атриуме (пещеры). 2. Вставить в него Теневое Сердце (Shadow Atrium). 3. Активировать Древний Ключ в шлюзе (Ancient Gateway), чтобы начать бой. Это самый сложный босс в игре.',
    loot: ['Теневой атриум', 'Фигурка Древнего Топливопряда', 'Набросок', 'Роза', 'Костяная броня', 'Костяной шлем', 'Теневое кадило'],
    group: 'caves',
  },
  {
    id: 'ancient-guardian',
    name: 'Древний Страж',
    imageUrl: 'https://static.wikia.nocookie.net/dont-starve-game/images/0/03/Ancient_Guardian.png',
    wikiUrl: 'https://dontstarve.fandom.com/wiki/Ancient_Guardian',
    description: 'Обитает в Лабиринте Руин. Похож на живую версию Механической Ладьи.',
    guide: 'Находится в конце Лабиринта в Руинах (пещеры). Чтобы найти его, нужно спуститься в пещеры, найти биом Руин, пройти через Лабиринт (полный пауков и сундуков). Страж находится на большой открытой площадке в конце.',
    loot: ['8 Мяса', 'Рог стража', 'Большой орнаментированный сундук (с ценным лутом)'],
    group: 'caves',
  },
  {
    id: 'ancient-herald',
    name: 'Древний Вестник',
    imageUrl: 'https://static.wikia.nocookie.net/dont-starve-game/images/1/16/Ancient_Herald.png',
    wikiUrl: 'https://dontstarve.fandom.com/wiki/Ancient_Herald',
    description: 'Появляется во время Апокалипсиса в дополнении Hamlet. Преследует игрока.',
    guide: 'Появляется только во время Апокалипсиса в DLC Hamlet. Апокалипсис наступает, когда Часы Апокалипсиса в Руинах Гамлета отсчитывают полное время (60 дней по умолчанию). Вестник будет появляться рядом с игроком и призывать мобов.',
    loot: ['5 Темных лоскутов', '2-3 Топлива ужаса', 'Чертеж Плаща вихря'],
    group: 'hamlet',
  },
  {
    id: 'antlion',
    name: 'Муравьиный Лев',
    imageUrl: 'https://static.wikia.nocookie.net/dont-starve-game/images/f/ff/Antlion.png',
    wikiUrl: 'https://dontstarve.fandom.com/wiki/Antlion',
    description: 'Появляется в пустыне летом. Требует подношений, иначе вызывает обвалы.',
    guide: 'Появляется в Оазисной пустыне (с озером) только летом. Обычно возникает на месте песчаной бури. Чтобы начать бой, нужно дать ему холодный термальный камень или заморозить его. Если не кормить его безделушками, он будет создавать кратеры под игроком.',
    loot: ['6-8 пустынных камней', '4 куска мяса', '2-4 камня', 'Безделушки', 'Чертеж ленивого пустынника'],
    group: 'seasonal',
  },
  {
    id: 'armored-bearger',
    name: 'Бронированный Медведь-барсук',
    imageUrl: 'https://static.wikia.nocookie.net/dont-starve-game/images/d/d9/Armored_Bearger.png',
    wikiUrl: 'https://dontstarve.fandom.com/wiki/Armored_Bearger',
    description: 'Появляется из трупа Медведя-барсука при активном Лунном разломе.',
    guide: 'Сначала нужно убить обычного Медведя-барсука. Если в мире активен Лунный разлом (Lunar Rift), то труп Медведя не исчезнет сразу. К нему подлетит дух (Brightshade Gestalt) и вселится, превратив его в Бронированного Медведя-барсука. \n\n**Как активировать Лунный разлом:** Победите Небесного Чемпиона. После этого в мире появится Лунный разлом, который со временем будет расти и усиливать мобов.',
    loot: ['8 Мяса', '1 Густой мех', 'Чистый ужас'],
    group: 'lunar',
  },
  {
    id: 'bearger',
    name: 'Медведь-барсук',
    imageUrl: 'https://static.wikia.nocookie.net/dont-starve-game/images/8/88/Bearger.png',
    wikiUrl: 'https://dontstarve.fandom.com/wiki/Bearger',
    description: 'Приходит осенью в поисках еды. Любит мед и разоряет ульи.',
    guide: 'Приходит к игроку во вторую и последующие осени. Его слышно по рычанию. Он ищет еду (особенно мед) и разрушает постройки. Можно использовать его для рубки леса.',
    loot: ['8 Мяса', '1 Густой мех'],
    group: 'seasonal',
  },
  {
    id: 'bee-queen',
    name: 'Королева Пчел',
    imageUrl: 'https://static.wikia.nocookie.net/dont-starve-game/images/6/63/Bee_Queen.png',
    wikiUrl: 'https://dontstarve.fandom.com/wiki/Bee_Queen',
    description: 'Появляется из Гигантского улья, если ударить по нему молотом.',
    guide: 'Найдите Гигантский Улей (Gigantic Beehive) в биоме с обычной травой (обычно там много обычных ульев). Ударьте по нему молотом несколько раз, чтобы призвать Королеву. Она оставляет после себя след меда, замедляющий игрока.',
    loot: ['6-7 Меда', '1-2 Пчелиного маточного молочка', 'Корона королевы пчел', '1-2 Жала', 'Набросок'],
    group: 'surface',
  },
  {
    id: 'celestial-champion',
    name: 'Небесный Чемпион',
    imageUrl: 'https://static.wikia.nocookie.net/dont-starve-game/images/2/2c/Celestial_Champion_Phase_1.png',
    wikiUrl: 'https://dontstarve.fandom.com/wiki/Celestial_Champion',
    description: 'Призывается на Лунном острове после активации трех алтарей.',
    guide: 'Сложный процесс призыва: 1. Найдите Лунный остров. 2. Активируйте 3 алтаря, вставив в них соответствующие части (находятся там же). 3. Победите Древнего краба (Crab King) и получите Жемчужину. 4. Пройдите квесты Вагстаффа (Wagstaff) и постройте "Лунную станцию". Чемпион прилетит на финал.',
    loot: ['Просветленный осколок', 'Небесная сфера', 'Сдержанное статическое электричество', 'Лунное стекло'],
    group: 'lunar',
  },
  {
    id: 'celestial-revenant',
    name: 'Небесный Ревенант',
    imageUrl: 'https://static.wikia.nocookie.net/dont-starve/images/0/06/%D0%9D%D0%B5%D0%B1%D0%B5%D1%81%D0%BD%D1%8B%D0%B9_%D1%80%D0%B5%D0%B2%D0%B5%D0%BD%D0%B0%D0%BD%D1%82.png/revision/latest?cb=20250613122100&path-prefix=ru',
    wikiUrl: 'https://dont-starve.fandom.com/ru/wiki/%D0%9D%D0%B5%D0%B1%D0%B5%D1%81%D0%BD%D1%8B%D0%B9_%D1%80%D0%B5%D0%B2%D0%B5%D0%BD%D0%B0%D0%BD%D1%82',
    description: 'Мини-босс. Падает с неба на остров отшельницы после создания шестерых приспешников В.О.И.Н.Б.О.Т.а.',
    guide: 'Падает с неба на остров отшельницы после того, как Вагстафф или персонажи создают шестерых приспешников В.О.И.Н.Б.О.Т.а. Представляет из себя улучшенную версию первой фазы Небесного Защитника: обладает такими же атаками, но наносит дополнительный сквозной урон и имеет естественную защиту. После смерти рассыпается на куски, обнажая чистого гештальта.',
    loot: ['Чистый гештальт (после распада)'],
    group: 'lunar',
  },
  {
    id: 'celestial-scion',
    name: 'Небесный Отпрыск',
    imageUrl: 'https://static.wikia.nocookie.net/dont-starve/images/c/c8/%D0%9D%D0%B5%D0%B1%D0%B5%D1%81%D0%BD%D1%8B%D0%B9_%D0%BE%D1%82%D0%BF%D1%80%D1%8B%D1%81%D0%BA.png/revision/latest?cb=20250613202558&path-prefix=ru',
    wikiUrl: 'https://dont-starve.fandom.com/ru/wiki/%D0%9F%D1%80%D0%BE%D1%81%D0%B2%D0%B5%D1%82%D0%BB%D1%91%D0%BD%D0%BD%D1%8B%D0%B9_%D0%92.%D0%9E.%D0%98.%D0%9D.%D0%91.%D0%9E.%D0%A2.#%D0%9D%D0%B5%D0%B1%D0%B5%D1%81%D0%BD%D1%8B%D0%B9_%D0%BE%D1%82%D0%BF%D1%80%D1%8B%D1%81%D0%BA',
    description: 'Финальный босс лунной сюжетной арки. Появляется после поломки Просветлённого В.О.И.Н.Б.О.Т.а.',
    guide: 'Появляется после победы над Просветлённым В.О.И.Н.Б.О.Т.ом, когда могучая лунная сущность берёт под контроль внутренности машины. Использует атаку "сверхновая", от которой нужно прятаться за ногами В.О.И.Н.Б.О.Т.а (остаются после поломки предыдущей фазы).',
    loot: ['Просветленный осколок', 'Небесная сфера'],
    group: 'lunar',
  },
  {
    id: 'enlightened-warbis',
    name: 'Просветлённый В.О.И.Н.Б.О.Т',
    imageUrl: 'https://static.wikia.nocookie.net/dont-starve/images/e/e7/%D0%9F%D1%80%D0%BE%D1%81%D0%B2%D0%B5%D1%82%D0%BB%D1%91%D0%BD%D0%BD%D1%8B%D0%B9_%D0%92.%D0%9E.%D0%98.%D0%9D.%D0%91.%D0%9E.%D0%A2..png/revision/latest?cb=20250613203849&path-prefix=ru',
    wikiUrl: 'https://dont-starve.fandom.com/ru/wiki/%D0%9F%D1%80%D0%BE%D1%81%D0%B2%D0%B5%D1%82%D0%BB%D1%91%D0%BD%D0%BD%D1%8B%D0%B9_%D0%92.%D0%9E.%D0%98.%D0%9D.%D0%91.%D0%9E.%D0%A2.',
    description: 'В.О.И.Н.Б.О.Т., захваченный лунной сущностью. Его купол трескается, и над ним летают пять небесных драгоценностей.',
    guide: 'Финальный босс лунной сюжетной ветки. Изначально строится Вагстаффом на Острове отшельницы: нужно собрать 6 дронов (террамитов/трельцов), победить Небесного Ревенанта и зарядить машину капсулой с гештальтом. После победы над Небесным Отпрыском игроки могут заново построить В.О.И.Н.Б.О.Т.а, используя Фундамент. Для активации нужно полностью улучшить фундамент, разместить вокруг 6 приспешников, снова победить Ревенанта и зарядить робота капсулой. Построенный игроками робот сразу становится Просветлённым.',
    loot: ['Просветленный осколок', 'Небесная сфера'],
    group: 'lunar',
  },
  {
    id: 'crab-king',
    name: 'Король Крабов',
    imageUrl: 'https://static.wikia.nocookie.net/dont-starve-game/images/9/94/Crab_King.png',
    wikiUrl: 'https://dontstarve.fandom.com/wiki/Crab_King',
    description: 'Находится в море внутри кольца скал. Активируется вставкой камней.',
    guide: 'Найдите в море кольцо из скал (Sea Stacks) на карте. В центре будет инертный Король Крабов. Вставьте в него 9 самоцветов (любых, но от цвета зависят его способности), чтобы начать бой.',
    loot: ['7 Мяса', '9 Вставленных самоцветов', '4 Ракушечных колокольчика сопрано (50%)', 'Неактивное небесное подношение'],
    group: 'sea',
  },
  {
    id: 'crystal-deerclops',
    name: 'Кристальный Циклоп-олень',
    imageUrl: 'https://static.wikia.nocookie.net/dont-starve-game/images/8/8e/Crystal_Deerclops.png',
    wikiUrl: 'https://dontstarve.fandom.com/wiki/Crystal_Deerclops',
    description: 'Появляется, если убить Циклопа-оленя при активном Лунном разломе.',
    guide: 'Аналогично Бронированному Медведю. Убейте обычного Циклопа-оленя зимой, когда активен Лунный разлом. Труп реанимируется духом. \n\n**Как активировать Лунный разлом:** Победите Небесного Чемпиона. После этого в мире появится Лунный разлом, который со временем будет расти и усиливать мобов.',
    loot: ['8 Мяса', 'Глаз Циклопа-оленя', 'Чистый ужас'],
    group: 'lunar',
  },
  {
    id: 'deerclops',
    name: 'Циклоп-олень',
    imageUrl: 'https://static.wikia.nocookie.net/dont-starve-game/images/8/85/Deerclops.png',
    wikiUrl: 'https://dontstarve.fandom.com/wiki/Deerclops',
    description: 'Приходит зимой. Разрушает постройки и деревья.',
    guide: 'Приходит к игроку в ночь на 30-й день (первая зима) и далее каждую зиму. Его приближение сопровождается громким дыханием и тряской экрана. Нацелен на разрушение построек.',
    loot: ['8 Мяса', 'Глаз Циклопа-оленя'],
    group: 'seasonal',
  },
  {
    id: 'dragonfly',
    name: 'Драконья Муха',
    imageUrl: 'https://static.wikia.nocookie.net/dont-starve-game/images/8/84/Dragonfly.png',
    wikiUrl: 'https://dontstarve.fandom.com/wiki/Dragonfly',
    description: 'Обитает в пустыне круглый год. Плюется лавой.',
    guide: 'Всегда находится в Пустыне с перекати-поле (не Оазисной), возле лавовых озер. Она нейтральна, пока ее не атакуют. Периодически призывает лавовых личинок.',
    loot: ['Чешуя', '8 Мяса', 'Самоцветы', 'Золотые самородки', 'Яйцо лавовой личинки', 'Чертеж Чешуйчатой печи', 'Набросок'],
    group: 'surface',
  },
  {
    id: 'eye-of-terror',
    name: 'Глаз Террора',
    imageUrl: 'https://static.wikia.nocookie.net/dont-starve-game/images/b/b2/Eye_of_Terror_Phase_1.png',
    wikiUrl: 'https://dontstarve.fandom.com/wiki/Eye_of_Terror',
    description: 'Призывается ночью с помощью Террариума.',
    guide: 'Найдите в мире "Террариум" (сундук на ножках). Активируйте его ночью, чтобы призвать Глаз Террора. Босс улетает утром, если не убит.',
    loot: ['Маска-глаз', '1-3 Млечного белка'],
    group: 'surface',
  },
  {
    id: 'twins-of-terror',
    name: 'Близнецы Ужаса',
    imageUrl: 'https://static.wikia.nocookie.net/dont-starve-game/images/9/94/Retinazor_Phase_1.png',
    wikiUrl: 'https://dontstarve.fandom.com/wiki/Twins_of_Terror',
    description: 'Усиленная версия Глаза Террора. Два глаза вместо одного.',
    guide: 'Чтобы призвать их, нужно использовать "Кошмарный Террариум" (Nightmare Terrarium). Он создается путем добавления Топлива Ужаса в обычный Террариум во время боя с Глазом Террора или после него. Активируйте его ночью.',
    loot: ['Щит террора', '1-3 Млечного белка'],
    group: 'surface',
  },
  {
    id: 'frostjaw',
    name: 'Ледяная Челюсть',
    imageUrl: 'https://static.wikia.nocookie.net/dont-starve-game/images/4/48/Frostjaw.png',
    wikiUrl: 'https://dontstarve.fandom.com/wiki/Frostjaw',
    description: 'Обитает в океане. Можно выловить удочкой.',
    guide: 'Ищите в океане плавучую льдину с лункой для рыбалки. Используйте морскую удочку, чтобы "выловить" босса. Он выглядит как акула.',
    loot: ['1-3 Мяса', '1-3 Рыбьего мяса', 'Контрабандные побеги'],
    group: 'sea',
  },
  {
    id: 'grand-forge-boarrior',
    name: 'Великий Кузнечный Кабан-воин',
    imageUrl: 'https://static.wikia.nocookie.net/dont-starve-game/images/4/49/Grand_Forge_Boarrior.png',
    wikiUrl: 'https://dontstarve.fandom.com/wiki/Grand_Forge_Boarrior',
    description: 'Босс события The Forge. Появляется в 10-й волне.',
    guide: 'Эксклюзивный босс для ивента "The Forge". Появляется автоматически в конце 10-й волны врагов.',
    loot: ['Трофеи Кузни (Forge Loot)'],
    group: 'event',
  },
  {
    id: 'great-depths-worm',
    name: 'Великий Глубинный Червь',
    imageUrl: 'https://static.wikia.nocookie.net/dont-starve-game/images/7/78/Great_Depths_Worm.png',
    wikiUrl: 'https://dontstarve.fandom.com/wiki/Great_Depths_Worm',
    description: 'Редкий босс в пещерах. Заменяет волну глубинных червей.',
    guide: 'Может появиться в пещарах вместо обычной атаки глубинных червей (после 25 дня). Шанс появления растет с каждой волной.',
    loot: ['1-2 Монстромяса', 'Светящаяся ягода', 'Приманка великого глубинного червя'],
    group: 'caves',
  },
  {
    id: 'infernal-swineclops',
    name: 'Адский Свино-циклоп',
    imageUrl: 'https://static.wikia.nocookie.net/dont-starve-game/images/2/2b/Infernal_Swineclops.png',
    wikiUrl: 'https://dontstarve.fandom.com/wiki/Infernal_Swineclops',
    description: 'Финальный босс события The Forge.',
    guide: 'Финальный босс ивента "The Forge". Появляется после победы над Кабаном-воином.',
    loot: ['Трофеи Кузни (Forge Loot)'],
    group: 'event',
  },
  {
    id: 'iron-hulk',
    name: 'Железный Халк',
    imageUrl: 'https://static.wikia.nocookie.net/dont-starve-game/images/2/2e/Iron_Hulk_Ribs.png',
    wikiUrl: 'https://dontstarve.fandom.com/wiki/Iron_Hulk',
    description: 'Босс из дополнения Hamlet. Собирается из частей.',
    guide: 'В DLC Hamlet нужно найти три части Халка (голова, торс, ноги/руки) на разных островах. Соберите их в одном месте и активируйте молнией или телескопической дубинкой.',
    loot: ['1-3 Железной руды', '1-3 Шестеренки'],
    group: 'hamlet',
  },
  {
    id: 'klaus',
    name: 'Клаус',
    imageUrl: 'https://static.wikia.nocookie.net/dont-starve-game/images/e/e1/Klaus.png',
    wikiUrl: 'https://dontstarve.fandom.com/wiki/Klaus',
    description: 'Призывается зимой с помощью Ключа-рога, вставленного в Мешок с добром.',
    guide: 'Зимой в лесу (лиственном или обычном) появляется "Мешок с добром" (Loot Stash). Чтобы открыть его, нужно найти "Ключ-рог" (Deer Antler), который выпадает при попытке открыть мешок "Отмычкой" (получается с No-Eyed Deer). Вставьте рог в мешок, и появится Клаус.',
    loot: ['1-2 Древесного угля', 'Олений рог', 'Мешок с добром (содержит ценный лут)'],
    group: 'seasonal',
  },
  {
    id: 'lord-of-the-fruit-flies',
    name: 'Повелитель Фруктовых Мух',
    imageUrl: 'https://static.wikia.nocookie.net/dont-starve-game/images/b/b9/Lord_of_the_Fruit_Flies.png',
    wikiUrl: 'https://dontstarve.fandom.com/wiki/Lord_of_the_Fruit_Flies',
    description: 'Появляется возле больших скоплений фермерских культур.',
    guide: 'Появляется, если у игрока есть более 15 посаженных сельскохозяйственных культур, которые созрели или гниют. Шанс появления увеличивается со временем.',
    loot: ['Плод дружелюбной фруктовой мухи'],
    group: 'miniboss',
  },
  {
    id: 'malbatross',
    name: 'Мальбатрос',
    imageUrl: 'https://static.wikia.nocookie.net/dont-starve-game/images/e/e0/Malbatross.png',
    wikiUrl: 'https://dontstarve.fandom.com/wiki/Malbatross',
    description: 'Океанический босс. Можно найти по стае рыб.',
    guide: 'Ищите в глубоком океане стаю рыб ("Shoal"). С шансом 25% при приближении к ней появится Мальбатрос. Он пассивен, пока его не ударят.',
    loot: ['7 Мяса', '2 Синих самоцвета', '1-2 Пера Мальбатроса', '1-2 Наброска'],
    group: 'sea',
  },
  {
    id: 'moose-goose',
    name: 'Лось/Гусь',
    imageUrl: 'https://static.wikia.nocookie.net/dont-starve-game/images/d/dd/Goose.png',
    wikiUrl: 'https://dontstarve.fandom.com/wiki/Moose/Goose',
    description: 'Прилетает весной. Откладывает яйцо, из которого вылупляются лусята.',
    guide: 'Появляется весной (через 2-4 дня после начала) возле специальных гнезд (кучи веток), разбросанных по карте. Откладывает яйцо. Если его разбить или дождаться вылупления, появятся агрессивные лусята.',
    loot: ['6 Мяса', '2 Индюшачьи ножки', '3-5 Пуховых перьев'],
    group: 'seasonal',
  },
  {
    id: 'nightmare-werepig',
    name: 'Кошмарный Свинооборотень',
    imageUrl: 'https://static.wikia.nocookie.net/dont-starve-game/images/e/eb/Nightmare_Werepig.png',
    wikiUrl: 'https://dontstarve.fandom.com/wiki/Nightmare_Werepig',
    description: 'Скрытый босс в пещерах. Требует освобождения Свинооборотня от оков.',
    guide: 'В пещерах найдите биом с тремя столбами, к которым прикован Свинооборотень. Разрушьте столбы киркой/молотом. Свин освободится и превратится в босса.',
    loot: ['Чистый ужас', '1-3 Мяса', '1-3 Свиной кожи'],
    group: 'caves',
  },
  {
    id: 'palm-treeguard',
    name: 'Пальмовый Энт',
    imageUrl: 'https://static.wikia.nocookie.net/dont-starve-game/images/f/f4/Palm_Treeguard.png',
    wikiUrl: 'https://dontstarve.fandom.com/wiki/Palm_Treeguard',
    description: 'Появляется при рубке пальм в дополнении Shipwrecked.',
    guide: 'Аналог обычного Энта, но в DLC Shipwrecked. Появляется с небольшим шансом при рубке Кокосовых пальм. Кидается кокосами.',
    loot: ['Монстромясо', '1-2 Кокоса'],
    group: 'shipwrecked',
  },
  {
    id: 'possessed-varg',
    name: 'Одержимый Варг',
    imageUrl: 'https://static.wikia.nocookie.net/dont-starve-game/images/3/3b/Possessed_Varg.png',
    wikiUrl: 'https://dontstarve.fandom.com/wiki/Possessed_Varg',
    description: 'Появляется из Варга при активном Лунном разломе.',
    guide: 'Найдите след Варга (Varg) по следам коалослона (шанс появления растет с днями). Если убить Варга при активном Лунном разломе, он возродится как Одержимый. \n\n**Как активировать Лунный разлом:** Победите Небесного Чемпиона. После этого в мире появится Лунный разлом, который со временем будет расти и усиливать мобов.',
    loot: ['1-3 Мяса', '1-3 Монстромяса', '1-2 Чистого ужаса'],
    group: 'lunar',
  },
  {
    id: 'pugalisk',
    name: 'Пугалиск',
    imageUrl: 'https://static.wikia.nocookie.net/dont-starve-game/images/f/f6/Pugalisk.png',
    wikiUrl: 'https://dontstarve.fandom.com/wiki/Pugalisk',
    description: 'Босс из дополнения Hamlet. Вызывается у Фонтана молодости.',
    guide: 'В DLC Hamlet найдите Фонтан Молодости. Попробуйте набрать воду или что-то сделать с фонтаном, чтобы призвать Пугалиска.',
    loot: ['1-3 Мяса', '1-3 Монстромяса', '1-3 Змеиной кожи'],
    group: 'hamlet',
  },
  {
    id: 'quacken',
    name: 'Кракен',
    imageUrl: 'https://static.wikia.nocookie.net/dont-starve-game/images/9/9a/Quacken.png',
    wikiUrl: 'https://dontstarve.fandom.com/wiki/Quacken',
    description: 'Морской босс из Shipwrecked. Призывается тралением.',
    guide: 'В DLC Shipwrecked используйте Траловую сеть (Trawl Net) в глубоком океане. С шансом 5% (или выше в определенных местах) сеть выловит Кракена.',
    loot: ['Железный ключ', 'Мешок с трофеями', 'Сундук глубин'],
    group: 'shipwrecked',
  },
  {
    id: 'queen-womant',
    name: 'Королева Муравьев',
    imageUrl: 'https://static.wikia.nocookie.net/dont-starve-game/images/8/8d/Queen_Womant.png',
    wikiUrl: 'https://dontstarve.fandom.com/wiki/Queen_Womant',
    description: 'Босс из дополнения Hamlet. Обитает в Муравейнике.',
    guide: 'В DLC Hamlet найдите вход в Муравейник (Mant Hill). Пройдите вглубь до тронного зала Королевы.',
    loot: ['1-3 Мяса', '1-3 Монстромяса', '1-3 Паутины'],
    group: 'hamlet',
  },
  {
    id: 'reanimated-skeleton',
    name: 'Оживленный Скелет',
    imageUrl: 'https://static.wikia.nocookie.net/dont-starve-game/images/4/48/Reanimated_Skeleton_Forest.png',
    wikiUrl: 'https://dontstarve.fandom.com/wiki/Reanimated_Skeleton',
    description: 'Призывается ночью с помощью Теневого Атриума на собранном скелете.',
    guide: 'Соберите скелет из 8 окаменелостей (Fossils). Вставьте в него Теневое Сердце (Shadow Atrium), которое падает с Теневых Фигур 3-го уровня.',
    loot: ['8 Окаменелостей', 'Теневой атриум'],
    group: 'caves',
  },
  {
    id: 'scrappy-werepig',
    name: 'Металлический свин оборотень',
    imageUrl: 'https://static.wikia.nocookie.net/dont-starve-game/images/d/dd/Scrappy_Werepig.png',
    wikiUrl: 'https://dontstarve.fandom.com/wiki/Scrappy_Werepig',
    description: 'Вторая версия свина оборотня, которая появляется после победы над первым.',
    guide: 'Чтобы призвать его, нужно сначала победить Кошмарного Свинооборотня. После этого на поверхности на мусорной свалке появится Металлический свин.',
    loot: ['1-3 Мяса', '1-3 Свиной кожи', '1-2 Чистого ужаса'],
    group: 'caves',
  },
  {
    id: 'sealnado',
    name: 'Тюле-надо',
    imageUrl: 'https://static.wikia.nocookie.net/dont-starve-game/images/2/27/Sealnado.png',
    wikiUrl: 'https://dontstarve.fandom.com/wiki/Sealnado',
    description: 'Босс сезона ураганов в Shipwrecked. Торнадо с тюленем.',
    guide: 'В DLC Shipwrecked появляется в сезон Ураганов (Hurricane Season). Плавает по морю и засасывает игрока.',
    loot: ['3 Мяса', '2-3 Пуховых перьев', 'Лопасти турбины'],
    group: 'shipwrecked',
  },
  {
    id: 'shadow-pieces',
    name: 'Теневые Фигуры',
    imageUrl: 'https://static.wikia.nocookie.net/dont-starve-game/images/1/13/Shadow_Rook.png',
    wikiUrl: 'https://dontstarve.fandom.com/wiki/Shadow_Pieces',
    description: 'Призываются в новолуние с помощью мраморных статуй.',
    guide: 'Найдите мраморные статуи Коня, Слона и Ладьи. Принесите к ним соответствующие "Подозрительные мраморные части" (тяжелые, носятся на спине). Почините статуи. В Новолуние (New Moon) разбейте статуи киркой, чтобы освободить Теневые Фигуры.',
    loot: ['1-3 Топлива ужаса', '1-3 Шестеренки', 'Теневой атриум (на уровне 3)'],
    group: 'surface',
  },
  {
    id: 'spider-queen',
    name: 'Королева Пауков',
    imageUrl: 'https://static.wikia.nocookie.net/dont-starve-game/images/7/79/Spider_Queen.png',
    wikiUrl: 'https://dontstarve.fandom.com/wiki/Spider_Queen',
    description: 'Вырастает из кокона пауков 3-го уровня.',
    guide: 'Когда кокон пауков (Spider Den) достигает 3-го уровня (самый большой), через некоторое время он может превратиться в Королеву Пауков, которая будет бродить вокруг и создавать новые коконы.',
    loot: ['Монстромясо', 'Паутина', 'Паучьи яйца', 'Паучья шляпа'],
    group: 'miniboss',
  },
  {
    id: 'tiger-shark',
    name: 'Тигровая Акула',
    imageUrl: 'https://static.wikia.nocookie.net/dont-starve-game/images/4/45/Tiger_Shark.png',
    wikiUrl: 'https://dontstarve.fandom.com/wiki/Tiger_Shark',
    description: 'Босс из Shipwrecked. Обитает возле своего логова.',
    guide: 'В DLC Shipwrecked найдите логово Тигровой Акулы (большой песчаный холм на острове). Акула появляется, если игрок находится рядом с логовом или атакует акулят.',
    loot: ['2-4 Сырой рыбы', '1-2 Глаза тигровой акулы', '2-4 Акульих жабр'],
    group: 'shipwrecked',
  },
  {
    id: 'toadstool',
    name: 'Жаба-поганка',
    imageUrl: 'https://static.wikia.nocookie.net/dont-starve-game/images/a/a7/Toadstool.png',
    wikiUrl: 'https://dontstarve.fandom.com/wiki/Toadstool',
    description: 'Обитает в пещерах. Призывается ударом по грибу.',
    guide: 'В пещерах найдите три небольших пруда с фиолетовым грибом в центре (Toadstool Cap). Ударьте по грибу топором, чтобы призвать Жабу.',
    loot: ['Шкурка гриба', '1-3 Мяса', '1-3 Синих гриба', '1-3 Зеленых гриба', '1-3 Красных гриба', '1-2 Наброска'],
    group: 'caves',
  },
  {
    id: 'treeguard',
    name: 'Энт',
    imageUrl: 'https://static.wikia.nocookie.net/dont-starve-game/images/3/3c/Treeguard.png',
    wikiUrl: 'https://dontstarve.fandom.com/wiki/Treeguard',
    description: 'Появляется при рубке леса. Защитник деревьев.',
    guide: 'Появляется с небольшим шансом при рубке любых вечнозеленых деревьев. Шанс растет с количеством срубленных деревьев. Чтобы успокоить его, посадите шишки рядом.',
    loot: ['Монстромясо', '6 Живых бревен'],
    group: 'miniboss',
  },
  {
    id: 'rabbit-king',
    name: 'Кроль-король',
    imageUrl: 'https://static.wikia.nocookie.net/dont-starve-game/images/2/2c/Wrathful_Rabbit_King.png/revision/latest?cb=20240920200852',
    wikiUrl: 'https://dontstarve.fandom.com/wiki/Rabbit_King',
    description: 'Появляется, если убить слишком много кроликов или напасть на Благосклонного Кроль-короля.',
    guide: 'Чтобы призвать его, нужно убить 20-30 кроликов или напасть на Благосклонного Кроль-короля (который призывается 12-16 морковками в кроличью нору).',
    loot: ['1 Монстромясо', '2 Бороды', '1 Дубинка Кроль-короля'],
    group: 'miniboss',
  },
];
